prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: 8GB
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1500m
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 10Gi

grafana:
  defaultDashboardsTimezone: Asia/Shanghai
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

alertmanager:
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: cloud-ops
    alertmanagerConfigNamespaceSelector:
      matchLabels:
        cloud-ops-alerting: enabled
    alertmanagerConfigMatcherStrategy:
      type: None
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

